---
name: ⚒️ CI

##########################################################
on:
  push:
    branches:
      - '**'
      - '!dev-**'
      - '!dev/**'
      - '!hf**'
      - '!old**'
      - '!feature**'
    tags:
      - '**'
  pull_request:


##########################################################
jobs:

  ###########################
  rubocop:
    name: 'RuboCop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run tests
      run: bundle exec rubocop -c .rubocop.yml

  ###########################
  python_tests:
    name: Executing Python tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14" ]
    container: python:${{ matrix.python_version }}
    steps:

      - name: "Checking out sources."
        uses: actions/checkout@v6

      - name: Show Environment
        shell: bash
        run: |
          echo "::group::Bash enviroment:"
          env | sort
          echo "::endgroup::"
          echo -e "."
          echo "::notice title=Execute Python tests::Testing Python version: $( python --version )"

      - name: "Update all packages."
        id: apt-update
        shell: bash
        run: |
          echo "."
          echo "Apt update ..."
          apt update --yes

          echo "."
          echo "::group::Apt list upgradeable ..."
          apt list --upgradeable
          echo "::endgroup::"

          echo "."
          echo "::group::APT dist-upgrade ..."
          apt dist-upgrade --yes
          echo "::endgroup::"

      - name: "Install and execute lsb-release and jq."
        shell: bash
        run: |
          echo "::group::Installing lsb-release and jq"
          apt install --yes lsb-release jq || true
          echo "::endgroup::"
          echo "LSB-Release:"
          lsb_release -a

      - name: "Creating Python virtual environment."
        id: create-python-virtenv
        shell: bash
        run: |
          if [[ -d .venv ]] ; then
              echo "Removing existing virtual env '.venv' ..."
              rm -rfv .venv
          fi

          python3 -m venv .venv

      - name: "Update Pip and install fb-tools in virtual environment."
        id: update-pip
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          echo "::group::Update Pip in virtual environment ..."
          pip install --upgrade --upgrade-strategy eager pip
          echo "::endgroup::"

          echo "::group::Install fb-tools in virtual environment ..."
          pip install --upgrade --upgrade-strategy eager fb-tools
          echo "::endgroup::"

          if [[ "${{ matrix.python_version }}" =~ 3\.([4-9]|10)$ ]] ; then
              echo "::group::Install tomli in virtual environment ..."
              pip install --upgrade --upgrade-strategy eager tomli
              echo "::endgroup::"
          fi

      - name: "Installing mandatory Pip packages."
        id: install-mandatory-pip-packages
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          declare -a pkgs=()
          oifs="${IFS}"

          IFS=$'\n'
          for pkg in $( config-convert pyproject.toml -T json | jq -r .project.dependencies[] ) ; do
              pkgs+=( "${pkg}" )
          done
          IFS="${oifs}"

          if [[ "${#pkgs[*]}" -ge 1 ]] ; then
              echo "Mandatory Python packages: ${pkgs}"
              echo "::group::Install mandatory packages ..."
              cmd="pip install ${PIP_OPTIONS} --upgrade --upgrade-strategy eager"
              for pkg in "${pkgs[@]}" ; do
                  cmd+=" \"${pkg}\""
              done
              echo "."
              echo "Executing: ${cmd}"
              eval ${cmd}
          else
              echo "Did not found any mandatory packages."
          fi

      - name: "Installing testing Pip packages."
        id: install-testing-pip-packages
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          declare -a pkgs=()

          oifs="${IFS}"

          echo "Searching for testing modules ..."
          found_testing="n"
          IFS=$'\n'
          for group in $( config-convert pyproject.toml -T json | jq -r '.project."optional-dependencies" | keys[]' ) ; do
              if [[ "${group}" == "testing" ]] ; then
                  found_testing="y"
                  break
              fi
          done
          IFS="${oifs}"

          if [[ "${found_testing}" == "y" ]] ; then
              IFS=$'\n'
              for pkg in $( config-convert pyproject.toml -T json | jq -r ".project.\"optional-dependencies\".\"testing\"[]" ) ; do
                  pkgs+=( "${pkg}" )
              done
              IFS="${oifs}"

              if [[ "${#pkgs[*]}" -ge 1 ]] ; then
                  echo "Testing Python packages: ${pkgs}"
                  echo "::group::Install testing packages ..."
                  cmd="pip install ${PIP_OPTIONS} --upgrade --upgrade-strategy eager"
                  for pkg in "${pkgs[@]}" ; do
                      cmd+=" \"${pkg}\""
                  done
                  echo "."
                  echo "Executing: ${cmd}"
                  eval ${cmd}
              else
                  echo "Did not found any testing packages."
              fi
          else
              echo "Did not found testing package group."
          fi

      - name: "Executing Pytest."
        id: exec-pytest
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          echo "Executing Pytest ..."
          pytest --verbose

  ###########################
  python_linter:
    runs-on: ubuntu-latest
    name: Executing Python Linters
    container: python:3.14
    needs:
      - python_tests
    steps:

      - name: "Checking out sources."
        uses: actions/checkout@v6

      - name: Show Environment
        shell: bash
        run: |
          echo "::group::Bash enviroment:"
          env | sort
          echo "::endgroup::"
          echo -e "."
          echo "::notice title=Execute Python linter checks with Python 3.14"

      - name: "Update all packages."
        id: apt-update
        shell: bash
        run: |
          echo "."
          echo "Apt update ..."
          apt update --yes

          echo "."
          echo "::group::Apt list upgradeable ..."
          apt list --upgradeable
          echo "::endgroup::"

          echo "."
          echo "::group::APT dist-upgrade ..."
          apt dist-upgrade --yes
          echo "::endgroup::"

      - name: "Install and execute lsb-release, file, gawk and jq."
        shell: bash
        run: |
          echo "::group::Installing lsb-release, file, gawk and jq"
          apt install --yes lsb-release jq || true
          echo "::endgroup::"
          echo "LSB-Release:"
          lsb_release -a

      - name: "Creating Python virtual environment."
        id: create-python-virtenv
        shell: bash
        run: |
          if [[ -d .venv ]] ; then
              echo "Removing existing virtual env '.venv' ..."
              rm -rfv .venv
          fi

          python3 -m venv .venv

      - name: "Update Pip and install fb-tools in virtual environment."
        id: update-pip
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          echo "::group::Update Pip in virtual environment ..."
          pip install --upgrade --upgrade-strategy eager pip
          echo "::endgroup::"

          echo "::group::Install fb-tools in virtual environment ..."
          pip install --upgrade --upgrade-strategy eager fb-tools
          echo "::endgroup::"

          if [[ "${{ matrix.python_version }}" =~ 3\.([4-9]|10)$ ]] ; then
              echo "::group::Install tomli in virtual environment ..."
              pip install --upgrade --upgrade-strategy eager tomli
              echo "::endgroup::"
          fi

      - name: "Installing mandatory Pip packages."
        id: install-mandatory-pip-packages
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          declare -a pkgs=()
          oifs="${IFS}"

          IFS=$'\n'
          for pkg in $( config-convert pyproject.toml -T json | jq -r .project.dependencies[] ) ; do
              pkgs+=( "${pkg}" )
          done
          IFS="${oifs}"

          if [[ "${#pkgs[*]}" -ge 1 ]] ; then
              echo "Mandatory Python packages: ${pkgs}"
              echo "::group::Install mandatory packages ..."
              cmd="pip install ${PIP_OPTIONS} --upgrade --upgrade-strategy eager"
              for pkg in "${pkgs[@]}" ; do
                  cmd+=" \"${pkg}\""
              done
              echo "."
              echo "Executing: ${cmd}"
              eval ${cmd}
          else
              echo "Did not found any mandatory packages."
          fi

      - name: "Installing linter Pip packages."
        id: install-linter-pip-packages
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          declare -a pkgs=()

          oifs="${IFS}"

          echo "Searching for linter modules ..."
          found_lint="n"
          IFS=$'\n'
          for group in $( config-convert pyproject.toml -T json | jq -r '.project."optional-dependencies" | keys[]' ) ; do
              if [[ "${group}" == "lint" ]] ; then
                  found_lint="y"
                  break
              fi
          done
          IFS="${oifs}"

          if [[ "${found_lint}" == "y" ]] ; then
              IFS=$'\n'
              for pkg in $( config-convert pyproject.toml -T json | jq -r ".project.\"optional-dependencies\".\"lint\"[]" ) ; do
                  pkgs+=( "${pkg}" )
              done
              IFS="${oifs}"

              if [[ "${#pkgs[*]}" -ge 1 ]] ; then
                  echo "Testing Python packages: ${pkgs}"
                  echo "::group::Install lint packages ..."
                  cmd="pip install ${PIP_OPTIONS} --upgrade --upgrade-strategy eager"
                  for pkg in "${pkgs[@]}" ; do
                      cmd+=" \"${pkg}\""
                  done
                  echo "."
                  echo "Executing: ${cmd}"
                  eval ${cmd}
              else
                  echo "Did not found any lint packages."
              fi
          else
              echo "Did not found lint package group."
          fi

      - name: Execute Flake 8
        id: exec-flake9
        shell: bash
        run: |
          echo "Activating virtual environment ..."
          source .venv/bin/activate

          declare -a scripts=()
          oifs="${IFS}"

          echo "Collecting Python scripts ..."
          for script in $( file * | grep -i python | awk -F: '{print $1}' ) ; do
              scripts+=( "${script}" )
          done
          scripts+=( "monitoring" )
          scripts+=( "tests" )
          echo "Found Python scripts:"
          ls -l -d "${scripts[@]}"
          echo -e "."
          echo "And now finally executing flake8 ..."
          flake8 "${scripts[@]}"

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
